module.exports = Object.freeze({
    CHANNEL_EVENT_TYPE: 'EVENT',
    CHANNEL_VISIBILITY_OPEN: 'OPEN',
    PUSH_LOCALE_DE: 'de',
    RSVP_MAYBE: 'MAYBE',
    RSVP_YES: 'YES',
    EVENT_EDIT_TIME: 'EVENT_EDIT_TIME',
    EVENT_EDIT_VENUE: 'EVENT_EDIT_VENUE',
    EVENT_EDIT_DESCRIPTION: 'EVENT_EDIT_DESCRIPTION',
});